### ISSUE TITLE
Issues discovering lights from gui but not from lifxlan

### ISSUE THREAD

**Issue by tchesket** [frakman1/lifx-lan-gui#7] opened 2019-01-24 06:59 UTC
I will preface this by saying I am kind of brand-new to all this python coding, and I am terribly at coding in general. 

So I found this program along another called MaxLifx. Both of these programs (when installed using exe windows 10 installer) fail to find any lights. However, I installed python and downloaded the lifxlan utilities, and when I try to discover lights using those python utilities (which I thought this program used as a basis) it works every time. Doesn't throw any errors or do anything unusual. But for some reason these GUI utilities will not find anything. Please help

**Comment by tchesket** [comment] 2019-01-25 03:57
Also, another program I tried (that also uses lifxlan), called Lifx Control Panel, works perfectly fine. I don't really understand why this program is failing to discover the lights if lifx control panel uses the same method for discovery. Can anyone shed any light? (no pun intended)

**Comment by Mike-Skinner** [comment] 2019-05-10 11:13
Hi @tchesket,

LIFX Control Panel works reasonably well for me too - however my wireless access point has both 2.4Ghz and 5GHz networks - so sometimes I have to switch which one I am connected to on my laptop to control my LIFX bulb.

However, this lifx-lan-gui app looked perfect for me - as it runs on Linux.

Once I installed the pre-requisites (Lubuntu 16.04 LTS) - and was able to launch the app, it couldn't find my single LIFX bulb on my home network.

![image](https://user-images.githubusercontent.com/5193568/57523365-1fded100-7368-11e9-80e4-0a1ed54cab6a.png)

https://imgur.com/a/QF33EGa

I logged into my modem/router - found the device name and MAC address, then assigned it a static IP address (so it will not change). I then turned off the light physically, then turned it back on so it would be assigned the static/unchanging IP address.

Next I edited the lights.py file which came down with this GIT repository.
Specifically - these changes are from line 564 onwards. You can see I have specified my bulb label, IP address and MAC address (yours will be different). I'm a C# developer, not a Python developer - so unfortunately this approach only adds one lightbulb.

![image](https://user-images.githubusercontent.com/5193568/57523380-28cfa280-7368-11e9-815b-ec893fe2280c.png)

https://imgur.com/a/sxCvZOH

Then I started the app using python3 lights.py

The first time it crashed (if I recall - it was when I selected the single 'LED-IKEA-Lamp' option from the drop down list.

The second time I ran it, success:
![image](https://user-images.githubusercontent.com/5193568/57523391-3127dd80-7368-11e9-8a19-878e237cefd8.png)

https://imgur.com/a/WXX2uHY

I realise this is pretty hacky - and not a long term solution (especially if you have more than one LED).

@frakman1 - thanks for the time you spent on this project. I am grateful :-)

**Comment by frakman1** [comment] 2019-05-13 14:35
@Mike-Skinner My pleasure. I'm glad you find it useful.  I'm sorry that you are having trouble discovering your lights.

While developing, I recall I had problems too and I might have hardcoded a longer timeout within the lifx-lan python module. 
@mclarkk Is there a way to pass the timeout as an argument to the discover/init call?

In the meantime, try running the examples in [lifxlan](https://github.com/mclarkk/lifxlan) project and make sure those discovery calls are working first. Install it from source (instead of pip) and try changing the [timeout](https://github.com/mclarkk/lifxlan/blob/master/lifxlan/device.py#L35) to see if that helps.

**Comment by Mike-Skinner** [comment] 2019-05-13 16:31
@frakman1 - I've only got one LED (connected by 2.4 GHz wireless).

The lifx-lan-gui is running on a Linux NUC (my server, Ubuntu 16.04), which is connected via ethernet cable to my router/wireless-access-point (which has 2.4 GHz and 5 GHz stations).

I've downloaded the lifxlan project, and adjusted the timeout in device.py and the get_lights function. No luck - so I then started to look at other causes.

Bring down network interface which wasn't being used (in case it was interfering with which network to broadcast on):
 sudo ifconfig wlp2s0 down

Then I started looking at the ufw firewall configuration:

Allow the traffic between the Linux box (.250) and the lightbulb (.160)
 sudo ufw allow in on enp0s25 to 192.168.1.250 port 56700 proto udp
 sudo ufw allow out on enp0s25 to 192.168.1.160 port 56700 proto udp

But the thing that made it all start to work was the following (where .160 is the IP address of the light bulb):
 sudo ufw allow from 192.168.1.160

**Now lifx-lan-gui works, and liflxlan's "python3 hello_world.py 1" are finding the bulb without any problems :-)**

At the moment I'm just at the phase of turning the light on/off or changing the colour via VNC. I don't watch media on my Linux server - however it is hosting my media files and shared Kodi database.

Getting the lifx bulb to follow the movie playing on my arm/kodi media centre would be pretty cool - something for me to look into one weekend.

**Comment by frakman1** [comment] 2019-05-13 17:03
Glad you finally got it to work.
Ah yes, networking issues always seem to get in the way at some point. I ran into a [similar issue](https://github.com/mclarkk/lifxlan/issues/6) on Windows and had to enable broadcast messages on a the WiFi interface before it would work.

I know many people that use a Kodi plugin to get the LIFX experience while watching movies so I'm sure that can be done. Good luck!

**Comment by frakman1** [comment] 2019-09-09 20:53
@tchesket Were you able to finally discover your lights? You're right that it doesn't make sense for this to fail if **lifxlan** is working.

**Comment by ceboxsell** [comment] 2020-07-15 02:38
The issue is the code.
In finder, line 597 you have app.setCheckBox("Select All")
But that checkbox is commented out elsewhere so does not exist. Comment that line and all good.
I also am using LifxLAN without netifaces which is a pain and only there for python 2 I believe.
On Windows ifaddr works well for me, never an issue.

**Closed** 2022-06-12 21:01 UTC
