### ISSUE TITLE
"OSError: cannot identify image file" during desktop following

### ISSUE THREAD

**Issue by mclarkk** [frakman1/lifx-lan-gui#4] opened 2018-03-06 01:16 UTC
Was running the desktop-following in the background at work (so fun!), and I got the following error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "lights.py", line 685, in followDesktop
    image = ImageGrab.grab(bbox=box)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/ImageGrab.py", line 37, in grab
    im = Image.open(filepath)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/Image.py", line 2585, in open
    % (filename if filename else fp))
OSError: cannot identify image file '/var/folders/_j/jl71c2nx7m7cp5mgvry1rsgm0000gn/T/tmp2u7rek0l.png'
```

**Comment by frakman1** [comment] 2018-03-06 02:48
Hmm, looks like it might be a transient PIL/pillow error. Try changing [ line 686](https://github.com/frakman1/lifx-lan-gui/blob/master/lights.py#L686):
```python
image = ImageGrab.grab(bbox=box)
```
to:
```python
try:
     # take a screenshot
     image = ImageGrab.grab(bbox=box)
except Exception as e:
    print ("Ignoring error:", str(e))
```
and see if it recovers. Maybe there is a file descriptor that isn't getting freed in time.

**Comment by frakman1** [comment] 2018-03-06 19:44
I can confirm that I ran into this problem too. Adding the above code 'fixed' it haha

**Comment by frakman1** [comment] 2018-03-06 21:55
Addressed in commit: https://github.com/frakman1/lifx-lan-gui/commit/f6ce3900297afdf3369facb249310c0d4f57f5ff

**Closed** 2018-03-08 07:08 UTC
